name: Sync Leetcode

on:
  workflow_dispatch: # Allows manual trigger
  schedule:
    - cron: "30 16 * * *" # Runs every day at 4:30 PM UTC (10:00 PM IST)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: leetcode-problems
